### ISSUE TITLE
Compilation errors on Win32 (MSVC) for Ocaml 4

### ISSUE THREAD

**Issue by advancedwebdeveloper** [bashi-bazouk/Caravan#1]
ocamlc -c ZMQ.mli
ocamlc -c ZMQ.ml -I uint
ocamlc -c wrapper.c
wrapper.c
wrapper.c(47) : error C2275: value: недопустимое использование этого типа в качестве выражения
        c:\ocamlms\lib\caml\mlvalues.h(60): см. объявление "value"
wrapper.c(47) : error C2146: синтаксическая ошибка: отсутствие ";" перед идентификатором "values"
wrapper.c(47) : error C2065: values: необъявленный идентификатор
wrapper.c(47) : error C2143: синтаксическая ошибка: отсутствие ";" перед "тип"
wrapper.c(47) : error C2143: синтаксическая ошибка: отсутствие ";" перед "тип"
wrapper.c(48) : error C2065: values: необъявленный идентификатор
wrapper.c(51) : error C2065: values: необъявленный идентификатор
wrapper.c(52) : error C2065: values: необъявленный идентификатор
wrapper.c(53) : error C2065: values: необъявленный идентификатор
wrapper.c(56) : error C2065: values: необъявленный идентификатор
wrapper.c(59) : error C2061: синтаксическая ошибка: идентификатор "wrap_init"
wrapper.c(59) : error C2059: синтаксическая ошибка: ;
wrapper.c(59) : error C2059: синтаксическая ошибка: тип
wrapper.c(236) : error C2275: zmq_msg_t: недопустимое использование этого типа в качестве выражения
        C:\Documents and Settings\User.HOME-3D8A2273BA\Рабочий стол\ocaml-zmq-master\src\zmq.h(179): см. объявление "zmq_msg_t"
wrapper.c(236) : error C2146: синтаксическая ошибка: отсутствие ";" перед идентификатором "message"
wrapper.c(236) : error C2065: message: необъявленный идентификатор
wrapper.c(237) : error C2143: синтаксическая ошибка: отсутствие ";" перед "тип"
wrapper.c(239) : error C2065: rc: необъявленный идентификатор
wrapper.c(248) : error C2065: message: необъявленный идентификатор
wrapper.c(248) : warning C4133: функция: несовместимые типы - из "int _" в "zmq_msg_t *"
wrapper.c(252) : error C2065: rc: необъявленный идентификатор
wrapper.c(252) : error C2065: message: необъявленный идентификатор
wrapper.c(252) : error C2198: zmq_send: слишком мало аргументов для вызова
wrapper.c(255) : error C2065: rc: необъявленный идентификатор
wrapper.c(278) : error C2061: синтаксическая ошибка: идентификатор "wrap_recv"
wrapper.c(278) : error C2059: синтаксическая ошибка: ;
wrapper.c(278) : error C2059: синтаксическая ошибка: тип
wrapper.c(345) : error C2065: ZMQ_SWAP: необъявленный идентификатор
wrapper.c(345) : error C2099: инициализатор не является константой
wrapper.c(348) : error C2065: ZMQ_RECOVERY_IVL_MSEC: необъявленный идентификатор
wrapper.c(348) : error C2099: инициализатор не является константой
wrapper.c(349) : error C2065: ZMQ_HWM: необъявленный идентификатор
wrapper.c(349) : error C2099: инициализатор не является константой
wrapper.c(355) : error C2065: ZMQ_MCAST_LOOP: необъявленный идентификатор
wrapper.c(355) : error C2099: инициализатор не является константой
wrapper.c(400) : error C2065: ZMQ_SWAP: необъявленный идентификатор
wrapper.c(400) : error C2051: значение выражения для варианта выбора не является константой
wrapper.c(403) : error C2065: ZMQ_RECOVERY_IVL_MSEC: необъявленный идентификатор
wrapper.c(403) : error C2051: значение выражения для варианта выбора не является константой
wrapper.c(407) : error C2065: ZMQ_HWM: необъявленный идентификатор
wrapper.c(407) : error C2051: значение выражения для варианта выбора не является константой
wrapper.c(424) : error C2065: ZMQ_MCAST_LOOP: необъявленный идентификатор
wrapper.c(424) : error C2051: значение выражения для варианта выбора не является константой
wrapper.c(493) : error C2065: ZMQ_SWAP: необъявленный идентификатор
wrapper.c(493) : error C2051: значение выражения для варианта выбора не является константой
wrapper.c(496) : error C2065: ZMQ_RECOVERY_IVL_MSEC: необъявленный идентификатор
wrapper.c(496) : error C2051: значение выражения для варианта выбора не является константой
wrapper.c(501) : error C2065: ZMQ_HWM: необъявленный идентификатор
wrapper.c(501) : error C2051: значение выражения для варианта выбора не является константой
wrapper.c(526) : error C2065: ZMQ_MCAST_LOOP: необъявленный идентификатор
wrapper.c(526) : error C2051: значение выражения для варианта выбора не является константой
makefile:5: recipe for target `wrapper.o' failed
make: *_\* [wrapper.o] Error 2

**Comment by bashi-bazouk** [comment]
I don't speak Russian man.  You can't compile a C file with ocamlc.
